/* -*- C++ -*- */
/* Generated by D:\Study\openDDS\OpenDDS-DDS\bin\opendds_idl version 3.12.2 (ACE version 6.5.0) running on input file ShapeInfo.idl */
#ifndef OPENDDS_IDL_GENERATED_SHAPEINFOTYPESUPPORTIMPL_H_UIQJL6
#define OPENDDS_IDL_GENERATED_SHAPEINFOTYPESUPPORTIMPL_H_UIQJL6
#include "ShapeInfoC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DdsDcpsC.h"
#include "ShapeInfoTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/TypeSupportImpl.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: ShapeDemo */



/* Begin STRUCT: ShapeInfo */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

void gen_find_size(const ShapeDemo::ShapeInfo& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const ShapeDemo::ShapeInfo& stru);

bool operator>>(Serializer& strm, ShapeDemo::ShapeInfo& stru);

size_t gen_max_marshaled_size(const ShapeDemo::ShapeInfo& stru, bool align);

size_t gen_max_marshaled_size(KeyOnly<const ShapeDemo::ShapeInfo> stru, bool align);

void gen_find_size(KeyOnly<const ShapeDemo::ShapeInfo> stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, KeyOnly<const ShapeDemo::ShapeInfo> stru);

bool operator>>(Serializer& strm, KeyOnly<ShapeDemo::ShapeInfo> stru);

template <>
struct MarshalTraits<ShapeDemo::ShapeInfo> {
  static bool gen_is_bounded_size() { return false; }
  static bool gen_is_bounded_key_size() { return true; }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace ShapeDemo {
// This structure supports use of std::map with a key
// defined by one or more #pragma DCPS_DATA_KEY lines.
struct  ShapeInfo_OpenDDS_KeyLessThan {
  bool operator()(const ShapeDemo::ShapeInfo&, const ShapeDemo::ShapeInfo&) const
  {
    // Eith no DCPS_DATA_KEYs, return false
    // to allow use of map with just one entry
    return false;
  }
};
}


namespace ShapeDemo {
class ShapeInfoTypeSupportImpl;
}

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {
template <>
struct DDSTraits<ShapeDemo::ShapeInfo> {
  typedef ShapeDemo::ShapeInfo MessageType;
  typedef ShapeDemo::ShapeInfoSeq MessageSequenceType;
  typedef ShapeDemo::ShapeInfoTypeSupport TypeSupportType;
  typedef ShapeDemo::ShapeInfoTypeSupportImpl TypeSupportTypeImpl;
  typedef ShapeDemo::ShapeInfoDataWriter DataWriterType;
  typedef ShapeDemo::ShapeInfoDataReader DataReaderType;
  typedef ShapeDemo::ShapeInfo_OpenDDS_KeyLessThan LessThanType;

  static const char* type_name () { return "ShapeDemo::ShapeInfo"; }
  static bool gen_has_key () { return false; }

  static size_t gen_max_marshaled_size(const MessageType& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const MessageType& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }

  static size_t gen_max_marshaled_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& x, bool align) { return ::OpenDDS::DCPS::gen_max_marshaled_size(x, align); }
  static void gen_find_size(const OpenDDS::DCPS::KeyOnly<const MessageType>& arr, size_t& size, size_t& padding) { ::OpenDDS::DCPS::gen_find_size(arr, size, padding); }
};
}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace ShapeDemo {
class  ShapeInfoTypeSupportImpl
  : public virtual OpenDDS::DCPS::LocalObject<ShapeInfoTypeSupport>
  , public virtual OpenDDS::DCPS::TypeSupportImpl
{
public:
  typedef OpenDDS::DCPS::DDSTraits<ShapeInfo> TraitsType;
  typedef ShapeInfoTypeSupport TypeSupportType;
  typedef ShapeInfoTypeSupport::_var_type _var_type;
  typedef ShapeInfoTypeSupport::_ptr_type _ptr_type;

  ShapeInfoTypeSupportImpl() {}
  virtual ~ShapeInfoTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType();
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */
  virtual bool has_dcps_key();
  const char* default_type_name() const;
  static ShapeInfoTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};
}

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<ShapeDemo::ShapeInfo>();
bool gen_skip_over(Serializer& ser, ShapeDemo::ShapeInfo*);

}  }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif

/* End STRUCT: ShapeInfo */

/* End MODULE: ShapeDemo */
#endif /* OPENDDS_IDL_GENERATED_SHAPEINFOTYPESUPPORTIMPL_H_UIQJL6 */
