// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\study\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "ShapeInfoTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "ShapeInfoTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\study\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for ShapeDemo::ShapeInfoTypeSupport.

ShapeDemo::ShapeInfoTypeSupport_ptr
TAO::Objref_Traits<ShapeDemo::ShapeInfoTypeSupport>::duplicate (
    ShapeDemo::ShapeInfoTypeSupport_ptr p)
{
  return ShapeDemo::ShapeInfoTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<ShapeDemo::ShapeInfoTypeSupport>::release (
    ShapeDemo::ShapeInfoTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

ShapeDemo::ShapeInfoTypeSupport_ptr
TAO::Objref_Traits<ShapeDemo::ShapeInfoTypeSupport>::nil (void)
{
  return ShapeDemo::ShapeInfoTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ShapeDemo::ShapeInfoTypeSupport>::marshal (
    const ShapeDemo::ShapeInfoTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



ShapeDemo::ShapeInfoTypeSupport::ShapeInfoTypeSupport (void)
{}

ShapeDemo::ShapeInfoTypeSupport::~ShapeInfoTypeSupport (void)
{
}

ShapeDemo::ShapeInfoTypeSupport_ptr
ShapeDemo::ShapeInfoTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ShapeInfoTypeSupport::_duplicate (
      dynamic_cast<ShapeInfoTypeSupport_ptr> (_tao_objref));
}

ShapeDemo::ShapeInfoTypeSupport_ptr
ShapeDemo::ShapeInfoTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ShapeInfoTypeSupport::_duplicate (
      dynamic_cast<ShapeInfoTypeSupport_ptr> (_tao_objref));
}

ShapeDemo::ShapeInfoTypeSupport_ptr
ShapeDemo::ShapeInfoTypeSupport::_nil (void)
{
  return 0;
}

ShapeDemo::ShapeInfoTypeSupport_ptr
ShapeDemo::ShapeInfoTypeSupport::_duplicate (ShapeInfoTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
ShapeDemo::ShapeInfoTypeSupport::_tao_release (ShapeInfoTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ShapeDemo::ShapeInfoTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:ShapeDemo/ShapeInfoTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* ShapeDemo::ShapeInfoTypeSupport::_interface_repository_id (void) const
{
  return "IDL:ShapeDemo/ShapeInfoTypeSupport:1.0";
}

::CORBA::Boolean
ShapeDemo::ShapeInfoTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\study\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for ShapeDemo::ShapeInfoDataWriter.

ShapeDemo::ShapeInfoDataWriter_ptr
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataWriter>::duplicate (
    ShapeDemo::ShapeInfoDataWriter_ptr p)
{
  return ShapeDemo::ShapeInfoDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataWriter>::release (
    ShapeDemo::ShapeInfoDataWriter_ptr p)
{
  ::CORBA::release (p);
}

ShapeDemo::ShapeInfoDataWriter_ptr
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataWriter>::nil (void)
{
  return ShapeDemo::ShapeInfoDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataWriter>::marshal (
    const ShapeDemo::ShapeInfoDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



ShapeDemo::ShapeInfoDataWriter::ShapeInfoDataWriter (void)
{}

ShapeDemo::ShapeInfoDataWriter::~ShapeInfoDataWriter (void)
{
}

ShapeDemo::ShapeInfoDataWriter_ptr
ShapeDemo::ShapeInfoDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ShapeInfoDataWriter::_duplicate (
      dynamic_cast<ShapeInfoDataWriter_ptr> (_tao_objref));
}

ShapeDemo::ShapeInfoDataWriter_ptr
ShapeDemo::ShapeInfoDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ShapeInfoDataWriter::_duplicate (
      dynamic_cast<ShapeInfoDataWriter_ptr> (_tao_objref));
}

ShapeDemo::ShapeInfoDataWriter_ptr
ShapeDemo::ShapeInfoDataWriter::_nil (void)
{
  return 0;
}

ShapeDemo::ShapeInfoDataWriter_ptr
ShapeDemo::ShapeInfoDataWriter::_duplicate (ShapeInfoDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
ShapeDemo::ShapeInfoDataWriter::_tao_release (ShapeInfoDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ShapeDemo::ShapeInfoDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:ShapeDemo/ShapeInfoDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* ShapeDemo::ShapeInfoDataWriter::_interface_repository_id (void) const
{
  return "IDL:ShapeDemo/ShapeInfoDataWriter:1.0";
}

::CORBA::Boolean
ShapeDemo::ShapeInfoDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// d:\study\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:48
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for ShapeDemo::ShapeInfoDataReader.

ShapeDemo::ShapeInfoDataReader_ptr
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataReader>::duplicate (
    ShapeDemo::ShapeInfoDataReader_ptr p)
{
  return ShapeDemo::ShapeInfoDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataReader>::release (
    ShapeDemo::ShapeInfoDataReader_ptr p)
{
  ::CORBA::release (p);
}

ShapeDemo::ShapeInfoDataReader_ptr
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataReader>::nil (void)
{
  return ShapeDemo::ShapeInfoDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<ShapeDemo::ShapeInfoDataReader>::marshal (
    const ShapeDemo::ShapeInfoDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



ShapeDemo::ShapeInfoDataReader::ShapeInfoDataReader (void)
{}

ShapeDemo::ShapeInfoDataReader::~ShapeInfoDataReader (void)
{
}

ShapeDemo::ShapeInfoDataReader_ptr
ShapeDemo::ShapeInfoDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ShapeInfoDataReader::_duplicate (
      dynamic_cast<ShapeInfoDataReader_ptr> (_tao_objref));
}

ShapeDemo::ShapeInfoDataReader_ptr
ShapeDemo::ShapeInfoDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return ShapeInfoDataReader::_duplicate (
      dynamic_cast<ShapeInfoDataReader_ptr> (_tao_objref));
}

ShapeDemo::ShapeInfoDataReader_ptr
ShapeDemo::ShapeInfoDataReader::_nil (void)
{
  return 0;
}

ShapeDemo::ShapeInfoDataReader_ptr
ShapeDemo::ShapeInfoDataReader::_duplicate (ShapeInfoDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
ShapeDemo::ShapeInfoDataReader::_tao_release (ShapeInfoDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
ShapeDemo::ShapeInfoDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:ShapeDemo/ShapeInfoDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* ShapeDemo::ShapeInfoDataReader::_interface_repository_id (void) const
{
  return "IDL:ShapeDemo/ShapeInfoDataReader:1.0";
}

::CORBA::Boolean
ShapeDemo::ShapeInfoDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

