// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.0
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// d:\study\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:366


#include "ShapeInfoC.h"
#include "tao/CDR.h"

#if !defined (__ACE_INLINE__)
#include "ShapeInfoC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// d:\study\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_structure\cdr_op_cs.cpp:49

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const ShapeDemo::ShapeInfo &_tao_aggregate)
{
  return
    (strm << _tao_aggregate.shapeType.in ()) &&
    (strm << _tao_aggregate.id) &&
    (strm << _tao_aggregate.posX) &&
    (strm << _tao_aggregate.posY) &&
    (strm << _tao_aggregate.directionX) &&
    (strm << _tao_aggregate.directionY) &&
    (strm << _tao_aggregate.color) &&
    (strm << _tao_aggregate.size);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    ShapeDemo::ShapeInfo &_tao_aggregate)
{
  return
    (strm >> _tao_aggregate.shapeType.out ()) &&
    (strm >> _tao_aggregate.id) &&
    (strm >> _tao_aggregate.posX) &&
    (strm >> _tao_aggregate.posY) &&
    (strm >> _tao_aggregate.directionX) &&
    (strm >> _tao_aggregate.directionY) &&
    (strm >> _tao_aggregate.color) &&
    (strm >> _tao_aggregate.size);
}

TAO_END_VERSIONED_NAMESPACE_DECL



